"""Core package for CEXO optimization algorithms and utilities."""

from .config import (
    FACILITY_SPECS,
    FACILITY_COLORS,
    FACILITY_TYPES,
    FACILITY_CLEARANCE_BUFFER,
    PRACTICAL_BULLEEN_FACILITY_RANGES,
    PRACTICAL_BULLEEN_FACILITIES,
    BULLEEN_BOUNDARY_POLYGON,
    BULLEEN_ENTRANCES,
    BULLEEN_ROAD_POLYGONS,
    SiteConfig,
    Individual,
    MapElitesConfig,
    NSGA2Config,
    generate_facility_mix,
    get_practical_bulleen_facility_mix,
    sample_practical_bulleen_facility_mix,
    get_bulleen_boundary_polygon,
    get_bulleen_entrances,
    get_bulleen_road_polygons,
    get_site_bounds,
    point_in_polygon,
    get_facility_dimensions,
    facility_corners,
    facility_overlaps_polygon,
    facility_within_site_boundary,
    rectangles_overlap,
    calculate_overlap_area,
)
from .cexo_algorithm import CEXOArchive, CEXOOptimizer, ParetoFront

__all__ = [
    "FACILITY_SPECS",
    "FACILITY_COLORS",
    "FACILITY_TYPES",
    "FACILITY_CLEARANCE_BUFFER",
    "PRACTICAL_BULLEEN_FACILITY_RANGES",
    "PRACTICAL_BULLEEN_FACILITIES",
    "BULLEEN_BOUNDARY_POLYGON",
    "BULLEEN_ENTRANCES",
    "BULLEEN_ROAD_POLYGONS",
    "SiteConfig",
    "Individual",
    "MapElitesConfig",
    "NSGA2Config",
    "generate_facility_mix",
    "get_practical_bulleen_facility_mix",
    "sample_practical_bulleen_facility_mix",
    "get_bulleen_boundary_polygon",
    "get_bulleen_entrances",
    "get_bulleen_road_polygons",
    "get_site_bounds",
    "point_in_polygon",
    "get_facility_dimensions",
    "facility_corners",
    "facility_overlaps_polygon",
    "facility_within_site_boundary",
    "rectangles_overlap",
    "calculate_overlap_area",
    "ParetoFront",
    "CEXOArchive",
    "CEXOOptimizer",
]
